name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect node version
        id: detect-node-version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc' # detect node version from .nvmrc or .node-version
          cache: 'npm'  # Set cache to npm

      - name: Install dependencies
        run: npm ci  # Use npm ci for clean installs with lockfile

      - name: Build application
        run: npm run build  # Replace with your build command if different (e.g., npm run build)
        env:
          CI: 'true' # Disable interactive prompts during build, important for CI

      - name: Deploy to Vercel
        uses: vercel/vercel-action@v0.15.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Vercel project token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Vercel org id
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Vercel project id
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: yourdomain.com,www.yourdomain.com #optional
          working-directory: ./ #optional

      - name: Send Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: '#your-slack-channel' # Replace with your Slack channel
          SLACK_COLOR: '#FF0000'  # Red for failure
          SLACK_MESSAGE: 'Vercel deployment failed!'
          SLACK_TITLE: 'Deployment Failure'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }} # Replace with your Slack webhook URL

      - name: Send Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: '#your-slack-channel' # Replace with your Slack channel
          SLACK_COLOR: '#00FF00'  # Green for success
          SLACK_MESSAGE: 'Vercel deployment succeeded!'
          SLACK_TITLE: 'Deployment Success'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }} # Replace with your Slack webhook URL