name: Deploy Node App to Vercel

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or your preferred Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build  # Or your build command (e.g., `npm run build`, `yarn build`)

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./  # Adjust if your project isn't in the root
          vercel-args: '--prod' # Optional: Deploy to production

      - name: Discord Notification (Success)
        if: success()
        uses: appleboy/discord-action@v1.6.1
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "00FF00" #Green for success
          message: "🚀 Deployment to Vercel successful!"

      - name: Discord Notification (Failure)
        if: failure()
        uses: appleboy/discord-action@v1.6.1
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "FF0000" # Red for failure
          message: "❌ Deployment to Vercel failed! Check the logs."

      - name: Slack Notification (Success)
        if: success()
        uses: slackapi/slack-github-action@v2
        with:
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          status: success
          fields: commit,took
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification (Failure)
        if: failure()
        uses: slackapi/slack-github-action@v2
        with:
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}